version: 2
jobs:
  build:
    working_directory: ~/package
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Package
          command: |     
            npm install npm-cli-login
            yarn  
            yarn build
            yarn login
            yarn 2npm      