version: 2
jobs:
  build:
    working_directory: ~/package
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Package
          command: |     
            npm install -g npm-cli-login
            yarn  
            yarn build
            npm-cli-login -u $NPM_USERNAME -p $NPM_PASSWORD -e $NPM_EMAIL             
            npm run 2npm      