version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          context: 
            - NPM
jobs:
  build:
    working_directory: ~/package
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Package
          command: |     
            sudo npm install -g npm-cli-login publish
            yarn  
            yarn build
            npm run login
            npm run 2npm     